feat(crypto template): add new template crypto, fix issues
Signed-off-by: FX Soubirou <soubirou@yahoo.fr>

diff --git a/Taskfile.dist.yml b/Taskfile.dist.yml
--- a/Taskfile.dist.yml
+++ b/Taskfile.dist.yml
@@ -24,27 +24,45 @@ includes:
 tasks:
 
   install-templates:
-    #  summary: |
-    #    [CORE] Activate Tasks templates.
-    #    Usage: task [-t Taskfile.dist.yml] 10-t-activate TEMPLATE|T=<template1-name>,<template2-name> [FILE|F=Taskfile.dist.yml]
-    #
-    #    Arguments:
-    #    TEMPLATE | T List of the templates to activate separated by comma (required)
-    #     FILE | F     Taskfile path (optional, by default Taskfile.yml)
+    desc: "[CORE] Download/update tasks templates. Arguments: [PROXY|P=http://proxy:8080] [PROXY_CREDENTIALS|PC=username:password] (*)"
+    summary: |
+      [CORE] Download/update tasks templates.
+      Usage: task install-templates [PROXY|P=http://proxy_url:proxy_port] [PROXY_CREDENTIALS|PC=username:password]
+
+      Arguments:
+       PROXY | P               Proxy URL (optional)
+       PROXY_CREDENTIALS | PC  Proxy credentials username:password (optional)
+
+      Requirements:
+        - wget or curl
     vars:
-      TEMPLATE: '{{default .T .TEMPLATE}}'
+      PROXY: '{{default .P .PROXY}}'
+      D_PROXY: '{{default .TASK_PROXY .PROXY}}'
+      PROXY_CREDENTIALS: '{{default .PC .PROXY_CREDENTIALS}}'
+      TASK_TEMPLATES:
+        sh: task 00:00-get-list-templates
       FILE: '{{default .F .FILE}}'
       D_FILE: '{{default "Taskfile.yml" .FILE}}'
       BEGIN: "    # BEGIN-INCLUDES-TEMPLATES"
       PATTERN_BEGIN: "^{{.BEGIN}}"
-      PATTERN_END: "^    # END-INCLUDES-TEMPLATES"
+      END: "# END-INCLUDES-TEMPLATES"
     cmds:
+      - date > {{.FILE_TASK_START}}
+      - defer: rm -f {{.FILE_TASK_START}}
       - mkdir -p "{{.DIR_TASKFILES}}"
+      - if [ -z "{{.TASK_TEMPLATES}}" ]; then echo "Error TASK_TEMPLATES variable is empty in Taskfile.project.yml file" && exit 1; else echo "Download templates -> {{.TASK_TEMPLATES}}"; fi
+      - |
+        line_include_template_begin=$(grep -Fn '{{.BEGIN}}' "{{.D_FILE}}" | head -n 1 | cut -d ':' -f 1)
+        line_delete_begin=$(expr $line_include_template_begin + 1)
+        line_include_template_end=$(grep -Fn '{{.END}}' "{{.D_FILE}}" | head -n 1 | cut -d ':' -f 1)
+        line_delete_end=$(expr $line_include_template_end - 1)
+        if [ $line_delete_end -ge $line_delete_begin ]; then
+          sed -i'.bu' "${line_delete_begin},${line_delete_end}d" "{{.D_FILE}}"
+        fi
       - defer: rm -f "{{.D_FILE}}".bu
-      - sed -i'.bu' '/{{.PATTERN_BEGIN}}/,//{/{{.PATTERN_BEGIN}}/!{/^    \# END-INCLUDES-TEMPLATES/!d;};}' "{{.D_FILE}}"
       - |
         includes="{{.BEGIN}}"
-        for t in $(echo "{{.TEMPLATE}}" | tr "," " "); do
+        for t in $(echo "{{.TASK_TEMPLATES}}" | tr "," " "); do
           if echo "$t" | grep -q "\[" 2>/dev/null; then
             task=$(echo "$t" | cut -d '[' -f 1)
           else
@@ -54,7 +72,8 @@ tasks:
         done
         sed -i'.bu' "s={{.PATTERN_BEGIN}}=${includes}=g" "{{.D_FILE}}"
       - |
-        for t in $(echo "{{.TEMPLATE}}" | tr "," " "); do
+        templates_list=$(task 00:00-get-list-templates)
+        for t in $(echo "{{.TASK_TEMPLATES}}" | tr "," " "); do
           if echo "$t" | grep -q "\[" 2>/dev/null; then
             task=$(echo "$t" | cut -d '[' -f 1)
             v=$(echo "$t" | sed -e 's/.*\[\(.*\)\]/\1/')
@@ -64,11 +83,9 @@ tasks:
             version="main"
           fi
           echo "Download template: $task version: $version"
-          task download-template TEMPLATE=${task}.yml VERSION=$version PROXY={{.PROXY}} PROXY_CREDENTIALS={{.PROXY_CREDENTIALS}}
+          task download-template TEMPLATE=${task}.yml VERSION=$version PROXY={{.D_PROXY}} PROXY_CREDENTIALS={{.PROXY_CREDENTIALS}}
         done
-    preconditions:
-      - sh: test -n "{{.TEMPLATE}}" || test -n "{{.T}}"
-        msg: "TEMPLATE|T argument is required"
+      - echo "Install templates Start $(cat {{.FILE_TASK_START}}) - End $(date)"
     silent: true
 
   usage:
@@ -121,7 +138,8 @@ tasks:
         if [ ! -z "{{.D_FILE}}" ]; then
             printf "\033[0;33m[ %s: ]\033[0m " "00" && task --list -t "{{.D_FILE}}" || true
         fi
-        echo ""
+      - echo ""
+      - echo " <task install-templates [PROXY|P=http://proxy:8080]> to install or update templates (Variable TASK_TEMPLATES in Taskfile.project.yml file)."
       - echo " (*) <task usage TSK=task-name> will show the usage of the task."
     silent: true
 
